; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-extract-analysis -pass-remarks-analysis=loop-extract-analysis -debug-only=loop-extract-analysis -S < %s 2>&1 | FileCheck %s

%struct.dummy = type { double }

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #0

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #0

define void @alloca() {
; CHECK-LABEL: @alloca(
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    [[TEMP:%.*]] = alloca [[STRUCT_DUMMY:%.*]], i32 0, align 8
; CHECK-NEXT:    br label [[HEADER:%.*]]
; CHECK:       header:
; CHECK-NEXT:    br label [[LATCH:%.*]]
; CHECK:       latch:
; CHECK-NEXT:    br label [[HEADER]]
;
newFuncRoot:
  %temp = alloca %struct.dummy, i32 0, align 8
  br label %header

header:                                      ; preds = %latch, %newFuncRoot
  br label %latch

latch:                                      ; preds = %header
  br label %header
}

attributes #0 = { argmemonly nocallback nofree nosync nounwind willreturn }
